//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword_Heading
    {
        public int id { get; set; }
        public int heading_id { get; set; }
        public string text { get; set; }
        public decimal rating { get; set; }
    
        public virtual Heading_Word Heading_Word { get; set; }
    }
}
