//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Software
    {
        public int id { get; set; }
        public int software_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string softwareWindowName { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Software Software { get; set; }
        public virtual User User { get; set; }
    }
}
