//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clipboards> Clipboards { get; set; }
        public DbSet<Heading_Word> Heading_Word { get; set; }
        public DbSet<Keyword_Heading> Keyword_Heading { get; set; }
        public DbSet<Keyword_Word> Keyword_Word { get; set; }
        public DbSet<Log_Movie> Log_Movie { get; set; }
        public DbSet<Log_Software> Log_Software { get; set; }
        public DbSet<Log_Song> Log_Song { get; set; }
        public DbSet<Movie> Movie { get; set; }
        public DbSet<Software> Software { get; set; }
        public DbSet<Song> Song { get; set; }
        public DbSet<Text_Word> Text_Word { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Word> Word { get; set; }
    }
}
