//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Log_Movie = new HashSet<Log_Movie>();
        }
    
        public int id { get; set; }
        public string filename { get; set; }
        public string name { get; set; }
        public int software_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public int times { get; set; }
        public int length { get; set; }
    
        public virtual ICollection<Log_Movie> Log_Movie { get; set; }
        public virtual Software Software { get; set; }
    }
}
