//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF
    {
        public PDF()
        {
            this.Keyword_PDF = new HashSet<Keyword_PDF>();
        }
    
        public int id { get; set; }
        public string filename { get; set; }
        public System.DateTime timestamp { get; set; }
        public int software_id { get; set; }
    
        public virtual ICollection<Keyword_PDF> Keyword_PDF { get; set; }
        public virtual Software Software { get; set; }
    }
}
