//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Log_Song = new HashSet<Log_Song>();
        }
    
        public int id { get; set; }
        public string fileName { get; set; }
        public string name { get; set; }
        public string artist { get; set; }
        public string genre { get; set; }
        public long length { get; set; }
    
        public virtual ICollection<Log_Song> Log_Song { get; set; }
    }
}
