//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text_Word
    {
        public int id { get; set; }
        public int word_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string text { get; set; }
    
        public virtual Word Word { get; set; }
    }
}
